<?xml version="1.0"?>
<!DOCTYPE mame[
<!ELEMENT mame (game+)>
	<!ELEMENT game (description, year?, manufacturer, history?, biosset*, rom*, disk*, sample*, chip*, video?, sound?, input?, dipswitch*, driver?)>
		<!ATTLIST game name CDATA #REQUIRED>
		<!ATTLIST game sourcefile CDATA #IMPLIED>
		<!ATTLIST game runnable (yes|no) "yes">
		<!ATTLIST game cloneof CDATA #IMPLIED>
		<!ATTLIST game romof CDATA #IMPLIED>
		<!ATTLIST game sampleof CDATA #IMPLIED>
		<!ELEMENT description (#PCDATA)>
		<!ELEMENT year (#PCDATA)>
		<!ELEMENT manufacturer (#PCDATA)>
		<!ELEMENT biosset EMPTY>
			<!ATTLIST biosset name CDATA #REQUIRED>
			<!ATTLIST biosset description CDATA #REQUIRED>
			<!ATTLIST biosset default (yes|no) "no">
		<!ELEMENT rom EMPTY>
			<!ATTLIST rom name CDATA #REQUIRED>
			<!ATTLIST rom bios CDATA #IMPLIED>
			<!ATTLIST rom size CDATA #REQUIRED>
			<!ATTLIST rom crc CDATA #IMPLIED>
			<!ATTLIST rom md5 CDATA #IMPLIED>
			<!ATTLIST rom sha1 CDATA #IMPLIED>
			<!ATTLIST rom merge CDATA #IMPLIED>
			<!ATTLIST rom region CDATA #IMPLIED>
			<!ATTLIST rom offset CDATA #IMPLIED>
			<!ATTLIST rom status (baddump|nodump|good) "good">
			<!ATTLIST rom dispose (yes|no) "no">
			<!ATTLIST rom soundonly (yes|no) "no">
		<!ELEMENT disk EMPTY>
			<!ATTLIST disk name CDATA #REQUIRED>
			<!ATTLIST disk md5 CDATA #IMPLIED>
			<!ATTLIST disk sha1 CDATA #IMPLIED>
			<!ATTLIST disk region CDATA #IMPLIED>
			<!ATTLIST disk index CDATA #IMPLIED>
		<!ELEMENT sample EMPTY>
			<!ATTLIST sample name CDATA #REQUIRED>
		<!ELEMENT chip EMPTY>
			<!ATTLIST chip name CDATA #REQUIRED>
			<!ATTLIST chip type (cpu|audio) #REQUIRED>
			<!ATTLIST chip soundonly (yes|no) "no">
			<!ATTLIST chip clock CDATA #IMPLIED>
		<!ELEMENT video EMPTY>
			<!ATTLIST video screen (raster|vector) #REQUIRED>
			<!ATTLIST video orientation (vertical|horizontal) #REQUIRED>
			<!ATTLIST video width CDATA #IMPLIED>
			<!ATTLIST video height CDATA #IMPLIED>
			<!ATTLIST video aspectx CDATA #IMPLIED>
			<!ATTLIST video aspecty CDATA #IMPLIED>
			<!ATTLIST video refresh CDATA #REQUIRED>
		<!ELEMENT sound EMPTY>
			<!ATTLIST sound channels CDATA #REQUIRED>
		<!ELEMENT input EMPTY>
			<!ATTLIST input service (yes|no) "no">
			<!ATTLIST input tilt (yes|no) "no">
			<!ATTLIST input players CDATA #REQUIRED>
			<!ATTLIST input control CDATA #IMPLIED>
			<!ATTLIST input buttons CDATA #IMPLIED>
			<!ATTLIST input coins CDATA #IMPLIED>
		<!ELEMENT dipswitch (dipvalue*)>
			<!ATTLIST dipswitch name CDATA #REQUIRED>
			<!ELEMENT dipvalue EMPTY>
				<!ATTLIST dipvalue name CDATA #REQUIRED>
				<!ATTLIST dipvalue default (yes|no) "no">
		<!ELEMENT driver EMPTY>
			<!ATTLIST driver status (good|preliminary|test) #REQUIRED>
			<!ATTLIST driver color (good|imperfect|preliminary) #REQUIRED>
			<!ATTLIST driver sound (good|imperfect|preliminary) #REQUIRED>
			<!ATTLIST driver palettesize CDATA #REQUIRED>
]>
<mame>
  <game name="nam1975" sourcefile="neogeo.c" romof="neogeo">
    <description>NAM-1975</description>
    <year>1990</year>
    <manufacturer>SNK</manufacturer>
    <biosset name="euro" description="Europe MVS (Ver. 2)" default="yes" />
    <biosset name="euro-s1" description="Europe MVS (Ver. 1)" />
    <biosset name="us" description="US MVS (Ver. 2?)" />
    <biosset name="us-e" description="US MVS (Ver. 1)" />
    <biosset name="asia" description="Asia MVS (Ver. 3)" />
    <biosset name="japan" description="Japan MVS (Ver. 3)" />
    <biosset name="japan-s2" description="Japan MVS (Ver. 2)" />
    <rom name="001-p1.bin" size="524288" crc="cc9fc951" sha1="92f4e6ddeeb825077d92dbb70b50afea985f15c0" region="cpu1" offset="0" />
    <rom name="001-s1.bin" size="65536" crc="8ded55a5" sha1="27c8ffac16fbcc19c843d1b5b47ae8d8ef83d44a" region="gfx1" offset="0" />
    <rom name="sfix.sfx" merge="sfix.sfx" size="131072" crc="354029fc" sha1="4ae4bf23b4c2acff875775d4cbff5583893ce2a1" region="gfx2" offset="0" />
    <rom name="sp-s2.sp1" merge="sp-s2.sp1" bios="euro" size="131072" crc="9036d879" sha1="4f5ed7105b7128794654ce82b51723e16e389543" region="user1" offset="0" />
    <rom name="sp-s.sp1" merge="sp-s.sp1" bios="euro-s1" size="131072" crc="c7f2fa45" sha1="09576ff20b4d6b365e78e6a5698ea450262697cd" region="user1" offset="0" />
    <rom name="usa_2slt.bin" merge="usa_2slt.bin" bios="us" size="131072" crc="e72943de" sha1="5c6bba07d2ec8ac95776aa3511109f5e1e2e92eb" region="user1" offset="0" />
    <rom name="sp-e.sp1" merge="sp-e.sp1" bios="us-e" size="131072" crc="2723a5b5" sha1="5dbff7531cf04886cde3ef022fb5ca687573dcb8" region="user1" offset="0" />
    <rom name="asia-s3.rom" merge="asia-s3.rom" bios="asia" size="131072" crc="91b64be3" sha1="720a3e20d26818632aedf2c2fd16c54f213543e1" region="user1" offset="0" />
    <rom name="vs-bios.rom" merge="vs-bios.rom" bios="japan" size="131072" crc="f0e8f27d" sha1="ecf01eda815909f1facec62abf3594eaa8d11075" region="user1" offset="0" />
    <rom name="sp-j2.rom" merge="sp-j2.rom" bios="japan-s2" size="131072" crc="acede59c" sha1="b6f97acd282fd7e94d9426078a90f059b5e9dd91" region="user1" offset="0" />
    <rom name="sm1.sm1" merge="sm1.sm1" size="131072" crc="97cf998b" sha1="977387a7c76ef9b21d0b01fa69830e949a9a9626" region="cpu2" offset="0" />
    <rom name="001-m1.bin" size="65536" crc="cd088502" sha1="939f745cd576905f326e6246a2eed78e9fa88178" region="cpu2" offset="0" />
    <rom name="000-lo.lo" merge="000-lo.lo" size="65536" crc="e09e253c" sha1="2b1c719531dac9bb503f22644e6e4236b91e7cfc" region="gfx4" offset="0" />
    <rom name="001-v11.bin" size="524288" crc="a7c3d5e5" sha1="e3efc86940f91c53b7724c4566cfc21ea1a7a465" region="sound1" soundonly="yes" offset="0" />
    <rom name="001-v21.bin" size="524288" crc="55e670b3" sha1="a047049646a90b6db2d1882264df9256aa5a85e5" region="sound2" soundonly="yes" offset="0" />
    <rom name="001-v22.bin" size="524288" crc="ab0d8368" sha1="404114db9f3295929080b87a5d0106b40da6223a" region="sound2" soundonly="yes" offset="80000" />
    <rom name="001-v23.bin" size="524288" crc="df468e28" sha1="4e5d4a709a4737a87bba4083aeb788f657862f1a" region="sound2" soundonly="yes" offset="100000" />
    <rom name="001-c1.bin" size="524288" crc="32ea98e1" sha1="c2fb3fb7dd14523a4b4b7fbdb81f44cb4cc48239" region="gfx3" offset="0" />
    <rom name="001-c2.bin" size="524288" crc="cbc4064c" sha1="224c970fd060d841fd430c946ef609bb57b6d78c" region="gfx3" offset="1" />
    <rom name="001-c3.bin" size="524288" crc="0151054c" sha1="f24fb501a7845f64833f4e5a461bcf9dc3262557" region="gfx3" offset="100000" />
    <rom name="001-c4.bin" size="524288" crc="0a32570d" sha1="f108446ec7844fde25f7a4ab454f76d384bf5e52" region="gfx3" offset="100001" />
    <rom name="001-c5.bin" size="524288" crc="90b74cc2" sha1="89898da36db259180e5261ed45eafc99ca13e504" region="gfx3" offset="200000" />
    <rom name="001-c6.bin" size="524288" crc="e62bed58" sha1="d05b2903b212a51ee131e52c761b714cb787683e" region="gfx3" offset="200001" />
    <chip type="cpu" name="68000" clock="12000000" />
    <chip type="cpu" soundonly="yes" name="Z80" clock="4000000" />
    <chip type="audio" name="YM2610" clock="8000000" />
    <video screen="raster" orientation="horizontal" width="304" height="224" aspectx="4" aspecty="3" refresh="60.000000" />
    <sound channels="2" />
    <input players="2" control="joy8way" buttons="4" coins="2" />
    <dipswitch name="Test Switch">
      <dipvalue name="Off" default="yes" />
      <dipvalue name="On" />
    </dipswitch>
    <dipswitch name="Coin Chutes?">
      <dipvalue name="1?" />
      <dipvalue name="2?" default="yes" />
    </dipswitch>
    <dipswitch name="Autofire (in some games)">
      <dipvalue name="Off" default="yes" />
      <dipvalue name="On" />
    </dipswitch>
    <dipswitch name="COMM Setting">
      <dipvalue name="Off" default="yes" />
      <dipvalue name="1" />
      <dipvalue name="2" />
      <dipvalue name="3" />
      <dipvalue name="4" />
    </dipswitch>
    <dipswitch name="Free Play">
      <dipvalue name="Off" default="yes" />
      <dipvalue name="On" />
    </dipswitch>
    <dipswitch name="Freeze">
      <dipvalue name="Off" default="yes" />
      <dipvalue name="On" />
    </dipswitch>
    <driver status="good" color="good" sound="good" palettesize="4096" />
  </game>
  <game name="bstars" sourcefile="neogeo.c" romof="neogeo">
    <description>Baseball Stars Professional</description>
    <year>1990</year>
    <manufacturer>SNK</manufacturer>
    <biosset name="euro" description="Europe MVS (Ver. 2)" default="yes" />
    <biosset name="euro-s1" description="Europe MVS (Ver. 1)" />
    <biosset name="us" description="US MVS (Ver. 2?)" />
    <biosset name="us-e" description="US MVS (Ver. 1)" />
    <biosset name="asia" description="Asia MVS (Ver. 3)" />
    <biosset name="japan" description="Japan MVS (Ver. 3)" />
    <biosset name="japan-s2" description="Japan MVS (Ver. 2)" />
    <rom name="002-p1.bin" size="524288" crc="3bc7790e" sha1="50b2fffb1278151bb4849fbe1f8cb23916019815" region="cpu1" offset="0" />
    <rom name="002-s1.bin" size="131072" crc="1a7fd0c6" sha1="3fc701b7afddab369ddf9dedfbc5e1aaf80b8af3" region="gfx1" offset="0" />
    <rom name="sfix.sfx" merge="sfix.sfx" size="131072" crc="354029fc" sha1="4ae4bf23b4c2acff875775d4cbff5583893ce2a1" region="gfx2" offset="0" />
    <rom name="sp-s2.sp1" merge="sp-s2.sp1" bios="euro" size="131072" crc="9036d879" sha1="4f5ed7105b7128794654ce82b51723e16e389543" region="user1" offset="0" />
    <rom name="sp-s.sp1" merge="sp-s.sp1" bios="euro-s1" size="131072" crc="c7f2fa45" sha1="09576ff20b4d6b365e78e6a5698ea450262697cd" region="user1" offset="0" />
    <rom name="usa_2slt.bin" merge="usa_2slt.bin" bios="us" size="131072" crc="e72943de" sha1="5c6bba07d2ec8ac95776aa3511109f5e1e2e92eb" region="user1" offset="0" />
    <rom name="sp-e.sp1" merge="sp-e.sp1" bios="us-e" size="131072" crc="2723a5b5" sha1="5dbff7531cf04886cde3ef022fb5ca687573dcb8" region="user1" offset="0" />
    <rom name="asia-s3.rom" merge="asia-s3.rom" bios="asia" size="131072" crc="91b64be3" sha1="720a3e20d26818632aedf2c2fd16c54f213543e1" region="user1" offset="0" />
    <rom name="vs-bios.rom" merge="vs-bios.rom" bios="japan" size="131072" crc="f0e8f27d" sha1="ecf01eda815909f1facec62abf3594eaa8d11075" region="user1" offset="0" />
    <rom name="sp-j2.rom" merge="sp-j2.rom" bios="japan-s2" size="131072" crc="acede59c" sha1="b6f97acd282fd7e94d9426078a90f059b5e9dd91" region="user1" offset="0" />
    <rom name="sm1.sm1" merge="sm1.sm1" size="131072" crc="97cf998b" sha1="977387a7c76ef9b21d0b01fa69830e949a9a9626" region="cpu2" offset="0" />
    <rom name="002-m1.bin" size="65536" crc="79a8f4c2" sha1="08ca2b72fd9b0ed068dc918ecda51d13203a3481" region="cpu2" offset="0" />
    <rom name="000-lo.lo" merge="000-lo.lo" size="65536" crc="e09e253c" sha1="2b1c719531dac9bb503f22644e6e4236b91e7cfc" region="gfx4" offset="0" />
    <rom name="002-v11.bin" size="524288" crc="b7b925bd" sha1="644c92fa90e74998e73714f74b1e0680ee372a07" region="sound1" soundonly="yes" offset="0" />
    <rom name="002-v12.bin" size="524288" crc="329f26fc" sha1="2c8009edc88c6b26f7be5beb2b8d260aac394ee1" region="sound1" soundonly="yes" offset="80000" />
    <rom name="002-v13.bin" size="524288" crc="0c39f3c8" sha1="db8f8670639601215707d918d4fb93221460446a" region="sound1" soundonly="yes" offset="100000" />
    <rom name="002-v14.bin" size="524288" crc="c7e11c38" sha1="5abf2a7877e0162c758a4dcf09f183930fa7ef24" region="sound1" soundonly="yes" offset="180000" />
    <rom name="002-v21.bin" size="524288" crc="04a733d1" sha1="84159368c0f6de2c3b8121227201cd3422455cf6" region="sound2" soundonly="yes" offset="0" />
    <rom name="002-c1.bin" size="524288" crc="aaff2a45" sha1="c91ee72d1d74514df8ec44fca703409d92158ae3" region="gfx3" offset="0" />
    <rom name="002-c2.bin" size="524288" crc="3ba0f7e4" sha1="f023b134b9c7994f477867307d2732026033501d" region="gfx3" offset="1" />
    <rom name="002-c3.bin" size="524288" crc="96f0fdfa" sha1="9f779a1ae46aeda54d69382b074392ade687f62f" region="gfx3" offset="100000" />
    <rom name="002-c4.bin" size="524288" crc="5fd87f2f" sha1="a5dd6f26f9485f216c2428ae1792c182beb10dbc" region="gfx3" offset="100001" />
    <rom name="002-c5.bin" size="524288" crc="807ed83b" sha1="3268e7d4602c3f55f1e0da2c80653d5ae461ef67" region="gfx3" offset="200000" />
    <rom name="002-c6.bin" size="524288" crc="5a3cad41" sha1="c620d18f4ff32ed5489c941dfc641030a54f1c14" region="gfx3" offset="200001" />
    <chip type="cpu" name="68000" clock="12000000" />
    <chip type="cpu" soundonly="yes" name="Z80" clock="4000000" />
    <chip type="audio" name="YM2610" clock="8000000" />
    <video screen="raster" orientation="horizontal" width="320" height="224" aspectx="4" aspecty="3" refresh="60.000000" />
    <sound channels="2" />
    <input players="2" control="joy8way" buttons="4" coins="2" />
    <dipswitch name="Test Switch">
      <dipvalue name="Off" default="yes" />
      <dipvalue name="On" />
    </dipswitch>
    <dipswitch name="Coin Chutes?">
      <dipvalue name="1?" />
      <dipvalue name="2?" default="yes" />
    </dipswitch>
    <dipswitch name="Autofire (in some games)">
      <dipvalue name="Off" default="yes" />
      <dipvalue name="On" />
    </dipswitch>
    <dipswitch name="COMM Setting">
      <dipvalue name="Off" default="yes" />
      <dipvalue name="1" />
      <dipvalue name="2" />
      <dipvalue name="3" />
      <dipvalue name="4" />
    </dipswitch>
    <dipswitch name="Free Play">
      <dipvalue name="Off" default="yes" />
      <dipvalue name="On" />
    </dipswitch>
    <dipswitch name="Freeze">
      <dipvalue name="Off" default="yes" />
      <dipvalue name="On" />
    </dipswitch>
    <driver status="good" color="good" sound="good" palettesize="4096" />
  </game>
  <game name="tpgolf" sourcefile="neogeo.c" romof="neogeo">
    <description>Top Player's Golf</description>
    <year>1990</year>
    <manufacturer>SNK</manufacturer>
    <biosset name="euro" description="Europe MVS (Ver. 2)" default="yes" />
    <biosset name="euro-s1" description="Europe MVS (Ver. 1)" />
    <biosset name="us" description="US MVS (Ver. 2?)" />
    <biosset name="us-e" description="US MVS (Ver. 1)" />
    <biosset name="asia" description="Asia MVS (Ver. 3)" />
    <biosset name="japan" description="Japan MVS (Ver. 3)" />
    <biosset name="japan-s2" description="Japan MVS (Ver. 2)" />
    <rom name="003-p1.bin" size="524288" crc="f75549ba" sha1="3f7bdf5e2964e921fe1dd87c51a79a1a501fc73f" region="cpu1" offset="0" />
    <rom name="003-p2.bin" size="524288" crc="b7809a8f" sha1="1604c889592c9610668bff296de48a0d6906156d" region="cpu1" offset="80000" />
    <rom name="003-s1.bin" size="131072" crc="7b3eb9b1" sha1="39cd8bad9f8bfdeb8ac681b5b79ae5aa81c8dd5f" region="gfx1" offset="0" />
    <rom name="sfix.sfx" merge="sfix.sfx" size="131072" crc="354029fc" sha1="4ae4bf23b4c2acff875775d4cbff5583893ce2a1" region="gfx2" offset="0" />
    <rom name="sp-s2.sp1" merge="sp-s2.sp1" bios="euro" size="131072" crc="9036d879" sha1="4f5ed7105b7128794654ce82b51723e16e389543" region="user1" offset="0" />
    <rom name="sp-s.sp1" merge="sp-s.sp1" bios="euro-s1" size="131072" crc="c7f2fa45" sha1="09576ff20b4d6b365e78e6a5698ea450262697cd" region="user1" offset="0" />
    <rom name="usa_2slt.bin" merge="usa_2slt.bin" bios="us" size="131072" crc="e72943de" sha1="5c6bba07d2ec8ac95776aa3511109f5e1e2e92eb" region="user1" offset="0" />
    <rom name="sp-e.sp1" merge="sp-e.sp1" bios="us-e" size="131072" crc="2723a5b5" sha1="5dbff7531cf04886cde3ef022fb5ca687573dcb8" region="user1" offset="0" />
    <rom name="asia-s3.rom" merge="asia-s3.rom" bios="asia" size="131072" crc="91b64be3" sha1="720a3e20d26818632aedf2c2fd16c54f213543e1" region="user1" offset="0" />
    <rom name="vs-bios.rom" merge="vs-bios.rom" bios="japan" size="131072" crc="f0e8f27d" sha1="ecf01eda815909f1facec62abf3594eaa8d11075" region="user1" offset="0" />
    <rom name="sp-j2.rom" merge="sp-j2.rom" bios="japan-s2" size="131072" crc="acede59c" sha1="b6f97acd282fd7e94d9426078a90f059b5e9dd91" region="user1" offset="0" />
    <rom name="sm1.sm1" merge="sm1.sm1" size="131072" crc="97cf998b" sha1="977387a7c76ef9b21d0b01fa69830e949a9a9626" region="cpu2" offset="0" />
    <rom name="003-m1.bin" size="65536" crc="7851d0d9" sha1="d021cef958cc37ab170b78d7a4b3ae94947e4d13" region="cpu2" offset="0" />
    <rom name="000-lo.lo" merge="000-lo.lo" size="65536" crc="e09e253c" sha1="2b1c719531dac9bb503f22644e6e4236b91e7cfc" region="gfx4" offset="0" />
    <rom name="003-v11.bin" size="524288" crc="ff97f1cb" sha1="defa249d46ae220f7bfa70746f5202bbbcc3e5fe" region="sound1" soundonly="yes" offset="0" />
    <rom name="003-v21.bin" size="524288" crc="d34960c6" sha1="36d5877d5e42aab943f4d693159f4f3ad8b0addc" region="sound2" soundonly="yes" offset="0" />
    <rom name="003-v22.bin" size="524288" crc="9a5f58d4" sha1="2b580595e1820430a36f06fd3e0e0b8f7d686889" region="sound2" soundonly="yes" offset="80000" />
    <rom name="003-v23.bin" size="524288" crc="30f53e54" sha1="22461f88a56d272b78dbc23204c0c6816200532b" region="sound2" soundonly="yes" offset="100000" />
    <rom name="003-v24.bin" size="524288" crc="5ba0f501" sha1="ca02937a611a2c50c9e4b54f8fd4eaea09259894" region="sound2" soundonly="yes" offset="180000" />
    <rom name="003-c1.bin" size="524288" crc="0315fbaf" sha1="583c9253219c1026d81ee5e0cf5568683adc2633" region="gfx3" offset="0" />
    <rom name="003-c2.bin" size="524288" crc="b4c15d59" sha1="b0d8ec967f9b8e5216301c10b2d36912abce6515" region="gfx3" offset="1" />
    <rom name="003-c3.bin" size="524288" crc="b09f1612" sha1="03fbb5db4e377ce9cb4e65ddbc0b114c02e7bae1" region="gfx3" offset="100000" />
    <rom name="003-c4.bin" size="524288" crc="150ea7a1" sha1="13edc30144b56285ef37eb8aa6fb934704de18d8" region="gfx3" offset="100001" />
    <rom name="003-c5.bin" size="524288" crc="9a7146da" sha1="2fc83d13e3e9565919aab01bf2a1b028f433b547" region="gfx3" offset="200000" />
    <rom name="003-c6.bin" size="524288" crc="1e63411a" sha1="ee397e2f679042e87b37d95837af62bb95a72af9" region="gfx3" offset="200001" />
    <rom name="003-c7.bin" size="524288" crc="2886710c" sha1="1533dd935f0a8f92a0a3c47d1d2bc6d035454244" region="gfx3" offset="300000" />
    <rom name="003-c8.bin" size="524288" crc="422af22d" sha1="f67c844c34545de6ea187f5bfdf440dec8518532" region="gfx3" offset="300001" />
    <chip type="cpu" name="68000" clock="12000000" />
    <chip type="cpu" soundonly="yes" name="Z80" clock="4000000" />
    <chip type="audio" name="YM2610" clock="8000000" />
    <video screen="raster" orientation="horizontal" width="304" height="224" aspectx="4" aspecty="3" refresh="60.000000" />
    <sound channels="2" />
    <input players="2" control="joy8way" buttons="4" coins="2" />
    <dipswitch name="Test Switch">
      <dipvalue name="Off" default="yes" />
      <dipvalue name="On" />
    </dipswitch>
    <dipswitch name="Coin Chutes?">
      <dipvalue name="1?" />
      <dipvalue name="2?" default="yes" />
    </dipswitch>
    <dipswitch name="Autofire (in some games)">
      <dipvalue name="Off" default="yes" />
      <dipvalue name="On" />
    </dipswitch>
    <dipswitch name="COMM Setting">
      <dipvalue name="Off" default="yes" />
      <dipvalue name="1" />
      <dipvalue name="2" />
      <dipvalue name="3" />
      <dipvalue name="4" />
    </dipswitch>
    <dipswitch name="Free Play">
      <dipvalue name="Off" default="yes" />
      <dipvalue name="On" />
    </dipswitch>
    <dipswitch name="Freeze">
      <dipvalue name="Off" default="yes" />
      <dipvalue name="On" />
    </dipswitch>
    <driver status="good" color="good" sound="good" palettesize="4096" />
  </game>
  <game name="mahretsu" sourcefile="neogeo.c" romof="neogeo">
    <description>Mahjong Kyoretsuden</description>
    <year>1990</year>
    <manufacturer>SNK</manufacturer>
    <biosset name="euro" description="Europe MVS (Ver. 2)" default="yes" />
    <biosset name="euro-s1" description="Europe MVS (Ver. 1)" />
    <biosset name="us" description="US MVS (Ver. 2?)" />
    <biosset name="us-e" description="US MVS (Ver. 1)" />
    <biosset name="asia" description="Asia MVS (Ver. 3)" />
    <biosset name="japan" description="Japan MVS (Ver. 3)" />
    <biosset name="japan-s2" description="Japan MVS (Ver. 2)" />
    <rom name="004-p1.bin" size="524288" crc="fc6f53db" sha1="64a62ca4c8fb68954e06121399c9402278bd0467" region="cpu1" offset="0" />
    <rom name="004-s1.bin" size="65536" crc="b0d16529" sha1="1483a3459309596ee3ecff68bdbde0809d82dd7a" region="gfx1" offset="0" />
    <rom name="sfix.sfx" merge="sfix.sfx" size="131072" crc="354029fc" sha1="4ae4bf23b4c2acff875775d4cbff5583893ce2a1" region="gfx2" offset="0" />
    <rom name="sp-s2.sp1" merge="sp-s2.sp1" bios="euro" size="131072" crc="9036d879" sha1="4f5ed7105b7128794654ce82b51723e16e389543" region="user1" offset="0" />
    <rom name="sp-s.sp1" merge="sp-s.sp1" bios="euro-s1" size="131072" crc="c7f2fa45" sha1="09576ff20b4d6b365e78e6a5698ea450262697cd" region="user1" offset="0" />
    <rom name="usa_2slt.bin" merge="usa_2slt.bin" bios="us" size="131072" crc="e72943de" sha1="5c6bba07d2ec8ac95776aa3511109f5e1e2e92eb" region="user1" offset="0" />
    <rom name="sp-e.sp1" merge="sp-e.sp1" bios="us-e" size="131072" crc="2723a5b5" sha1="5dbff7531cf04886cde3ef022fb5ca687573dcb8" region="user1" offset="0" />
    <rom name="asia-s3.rom" merge="asia-s3.rom" bios="asia" size="131072" crc="91b64be3" sha1="720a3e20d26818632aedf2c2fd16c54f213543e1" region="user1" offset="0" />
    <rom name="vs-bios.rom" merge="vs-bios.rom" bios="japan" size="131072" crc="f0e8f27d" sha1="ecf01eda815909f1facec62abf3594eaa8d11075" region="user1" offset="0" />
    <rom name="sp-j2.rom" merge="sp-j2.rom" bios="japan-s2" size="131072" crc="acede59c" sha1="b6f97acd282fd7e94d9426078a90f059b5e9dd91" region="user1" offset="0" />
    <rom name="sm1.sm1" merge="sm1.sm1" size="131072" crc="97cf998b" sha1="977387a7c76ef9b21d0b01fa69830e949a9a9626" region="cpu2" offset="0" />
    <rom name="004-m1.bin" size="65536" crc="37965a73" sha1="61ad03c74169f9f50a37048fb74300ee926ee766" region="cpu2" offset="0" />
    <rom name="000-lo.lo" merge="000-lo.lo" size="65536" crc="e09e253c" sha1="2b1c719531dac9bb503f22644e6e4236b91e7cfc" region="gfx4" offset="0" />
    <rom name="004-v1.bin" size="524288" crc="b2fb2153" sha1="36e0cc8927b11105de40188af46f6cf532794c10" region="sound1" soundonly="yes" offset="0" />
    <rom name="004-v2.bin" size="524288" crc="8503317b" sha1="ab22f1aba1e977ab234a4f1d73dc6ed789dbeb85" region="sound1" soundonly="yes" offset="80000" />
    <rom name="004-v3.bin" size="524288" crc="4999fb27" sha1="2d4926a220ea21bdd5e816bb16f985fff089500a" region="sound2" soundonly="yes" offset="0" />
    <rom name="004-v4.bin" size="524288" crc="776fa2a2" sha1="e7d5a362ab7806b7b009700a435c815a20e8ec68" region="sound2" soundonly="yes" offset="80000" />
    <rom name="004-v5.bin" size="524288" crc="b3e7eeea" sha1="4d1e97f380702a3a06e7f954b4caddd9c4119d8f" region="sound2" soundonly="yes" offset="100000" />
    <rom name="004-c1.bin" size="524288" crc="f1ae16bc" sha1="df68feed4dcba1e1566032b01ebb7b478a1792bf" region="gfx3" offset="0" />
    <rom name="004-c2.bin" size="524288" crc="bdc13520" sha1="2bc4c996d019a4c539f6c3188ef18089e54b7efa" region="gfx3" offset="1" />
    <rom name="004-c3.bin" size="524288" crc="9c571a37" sha1="21388aeb92bb8e15a55a063701ca9df79e292127" region="gfx3" offset="100000" />
    <rom name="004-c4.bin" size="524288" crc="7e81cb29" sha1="5036f04df30cf6903bd1a8cc06ff6f015c24a74b" region="gfx3" offset="100001" />
    <chip type="cpu" name="68000" clock="12000000" />
    <chip type="cpu" soundonly="yes" name="Z80" clock="4000000" />
    <chip type="audio" name="YM2610" clock="8000000" />
    <video screen="raster" orientation="horizontal" width="304" height="224" aspectx="4" aspecty="3" refresh="60.000000" />
    <sound channels="2" />
    <input players="2" control="joy8way" buttons="4" coins="2" />
    <dipswitch name="Test Switch">
      <dipvalue name="Off" default="yes" />
      <dipvalue name="On" />
    </dipswitch>
    <dipswitch name="Coin Chutes?">
      <dipvalue name="1?" />
      <dipvalue name="2?" default="yes" />
    </dipswitch>
    <dipswitch name="Mahjong Control Panel">
      <dipvalue name="Off" />
      <dipvalue name="On" default="yes" />
    </dipswitch>
    <dipswitch name="COMM Setting">
      <dipvalue name="Off" default="yes" />
      <dipvalue name="1" />
      <dipvalue name="2" />
      <dipvalue name="3" />
      <dipvalue name="4" />
    </dipswitch>
    <dipswitch name="Free Play">
      <dipvalue name="Off" default="yes" />
      <dipvalue name="On" />
    </dipswitch>
    <dipswitch name="Freeze">
      <dipvalue name="Off" default="yes" />
      <dipvalue name="On" />
    </dipswitch>
    <driver status="good" color="good" sound="good" palettesize="4096" />
  </game>
  <game name="maglord" sourcefile="neogeo.c" romof="neogeo">
    <description>Magician Lord (set 1)</description>
    <year>1990</year>
    <manufacturer>Alpha Denshi Co.</manufacturer>
    <biosset name="euro" description="Europe MVS (Ver. 2)" default="yes" />
    <biosset name="euro-s1" description="Europe MVS (Ver. 1)" />
    <biosset name="us" description="US MVS (Ver. 2?)" />
    <biosset name="us-e" description="US MVS (Ver. 1)" />
    <biosset name="asia" description="Asia MVS (Ver. 3)" />
    <biosset name="japan" description="Japan MVS (Ver. 3)" />
    <biosset name="japan-s2" description="Japan MVS (Ver. 2)" />
    <rom name="005-p1.bin" size="524288" crc="bd0a492d" sha1="d043d3710cf2b0d2b3798008e65e4c7c3ead1af3" region="cpu1" offset="0" />
    <rom name="005-s1.bin" size="131072" crc="1c5369a2" sha1="db0dba0a7dced6c9ca929c5abda491b05d84199c" region="gfx1" offset="0" />
    <rom name="sfix.sfx" merge="sfix.sfx" size="131072" crc="354029fc" sha1="4ae4bf23b4c2acff875775d4cbff5583893ce2a1" region="gfx2" offset="0" />
    <rom name="sp-s2.sp1" merge="sp-s2.sp1" bios="euro" size="131072" crc="9036d879" sha1="4f5ed7105b7128794654ce82b51723e16e389543" region="user1" offset="0" />
    <rom name="sp-s.sp1" merge="sp-s.sp1" bios="euro-s1" size="131072" crc="c7f2fa45" sha1="09576ff20b4d6b365e78e6a5698ea450262697cd" region="user1" offset="0" />
    <rom name="usa_2slt.bin" merge="usa_2slt.bin" bios="us" size="131072" crc="e72943de" sha1="5c6bba07d2ec8ac95776aa3511109f5e1e2e92eb" region="user1" offset="0" />
    <rom name="sp-e.sp1" merge="sp-e.sp1" bios="us-e" size="131072" crc="2723a5b5" sha1="5dbff7531cf04886cde3ef022fb5ca687573dcb8" region="user1" offset="0" />
    <rom name="asia-s3.rom" merge="asia-s3.rom" bios="asia" size="131072" crc="91b64be3" sha1="720a3e20d26818632aedf2c2fd16c54f213543e1" region="user1" offset="0" />
    <rom name="vs-bios.rom" merge="vs-bios.rom" bios="japan" size="131072" crc="f0e8f27d" sha1="ecf01eda815909f1facec62abf3594eaa8d11075" region="user1" offset="0" />
    <rom name="sp-j2.rom" merge="sp-j2.rom" bios="japan-s2" size="131072" crc="acede59c" sha1="b6f97acd282fd7e94d9426078a90f059b5e9dd91" region="user1" offset="0" />
    <rom name="sm1.sm1" merge="sm1.sm1" size="131072" crc="97cf998b" sha1="977387a7c76ef9b21d0b01fa69830e949a9a9626" region="cpu2" offset="0" />
    <rom name="005-m1.bin" size="65536" crc="91ee1f73" sha1="f060728543333a99216cc2879f7666a1f4235068" region="cpu2" offset="0" />
    <rom name="000-lo.lo" merge="000-lo.lo" size="65536" crc="e09e253c" sha1="2b1c719531dac9bb503f22644e6e4236b91e7cfc" region="gfx4" offset="0" />
    <rom name="005-v11.bin" size="524288" crc="cc0455fd" sha1="a8ff4270e7705e263d25ff0b301f503bccea7e59" region="sound1" soundonly="yes" offset="0" />
    <rom name="005-v21.bin" size="524288" crc="f94ab5b7" sha1="2c16985102e3585e08622d8c54ac5c60425b9ff8" region="sound2" soundonly="yes" offset="0" />
    <rom name="005-v22.bin" size="524288" crc="232cfd04" sha1="61b66a9decbbd1f500a8c186615e7fd077c6861e" region="sound2" soundonly="yes" offset="80000" />
    <rom name="005-c1.bin" size="524288" crc="806aee34" sha1="3c32a0edbbddb694495b510c13979c44b83de8bc" region="gfx3" offset="0" />
    <rom name="005-c2.bin" size="524288" crc="34aa9a86" sha1="cec97e1ff7f91158040c629ba75742db82c4ae5e" region="gfx3" offset="1" />
    <rom name="005-c3.bin" size="524288" crc="c4c2b926" sha1="478bfafca21f5a1338808251a06ab405e6a9e65f" region="gfx3" offset="100000" />
    <rom name="005-c4.bin" size="524288" crc="9c46dcf4" sha1="4c05f3dc25777a87578ce09a6cefb3a4cebf3266" region="gfx3" offset="100001" />
    <rom name="005-c5.bin" size="524288" crc="69086dec" sha1="7fa47f4a765948813ebf366168275dcc3c42e951" region="gfx3" offset="200000" />
    <rom name="005-c6.bin" size="524288" crc="ab7ac142" sha1="e6ad2843947d35d8e913d2666f87946c1ba7944f" region="gfx3" offset="200001" />
    <chip type="cpu" name="68000" clock="12000000" />
    <chip type="cpu" soundonly="yes" name="Z80" clock="4000000" />
    <chip type="audio" name="YM2610" clock="8000000" />
    <video screen="raster" orientation="horizontal" width="320" height="224" aspectx="4" aspecty="3" refresh="60.000000" />
    <sound channels="2" />
    <input players="2" control="joy8way" buttons="4" coins="2" />
    <dipswitch name="Test Switch">
      <dipvalue name="Off" default="yes" />
      <dipvalue name="On" />
    </dipswitch>
    <dipswitch name="Coin Chutes?">
      <dipvalue name="1?" />
      <dipvalue name="2?" default="yes" />
    </dipswitch>
    <dipswitch name="Autofire (in some games)">
      <dipvalue name="Off" default="yes" />
      <dipvalue name="On" />
    </dipswitch>
    <dipswitch name="COMM Setting">
      <dipvalue name="Off" default="yes" />
      <dipvalue name="1" />
      <dipvalue name="2" />
      <dipvalue name="3" />
      <dipvalue name="4" />
    </dipswitch>
    <dipswitch name="Free Play">
      <dipvalue name="Off" default="yes" />
      <dipvalue name="On" />
    </dipswitch>
    <dipswitch name="Freeze">
      <dipvalue name="Off" default="yes" />
      <dipvalue name="On" />
    </dipswitch>